spring:
    datasource:
        url: jdbc:mysql://localhost:3306/API_REST_GDS?createDatabaseIfNotExist=true&userSSL=false&useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
        username: root
        password:
        driver-class-name: com.mysql.cj.jdbc.Driver

## Specify DBMS

    jpa:
        database: MYSQL
        show-sql: false

## Hibernate DDL Auto (create, create-drop, update)
        hibernate:
            ddl-auto: update
        properties:
            hibernate:
                dialect: org.hibernate.dialect.MySQLDialect

server:
    port: 8081

flickr:
    apiKey: 6163b95181e9ea75ef2e39f1fd013a60
    apiSecret: 5ca96bb5c00d54b7
    appKey: 72157720885047970-7ba88d289c150e15
    appSecret: 722873850fb5ca7c
